version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    links:
      - db
    environment:
      POSTGRES_USER: flask_psql
      POSTGRES_PASSWORD: flask_psql
      POSTGRES_DB: flask_psql_dev
      POSTGRES_HOST: db
    entrypoint: ./entrypoint.sh
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: flask_psql
      POSTGRES_PASSWORD: flask_psql
      POSTGRES_DB: flask_psql_dev
