"""empty message

Revision ID: 9c166a235730
Revises: 
Create Date: 2020-05-18 21:54:06.390429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c166a235730'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=60), server_default='Anonymous', nullable=False),
    sa.Column('title', sa.String(length=80), server_default='', nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
